name: main
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  packages:
    name: test packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build with nix
        run: nix build
        working-directory: rust
      - name: Build with cargo
        run: cargo build
        working-directory: rust
